
Y = int(input('Digite um número para ver sua tabuada: '))
print('_'*16)
print('{} X {:2} = {}'.format(Y, 1, Y*1))
print('{} X {:2} = {}'.format(Y, 2, Y*2))
print('{} X {:2} = {}'.format(Y, 3, Y*3))
print('{} X {:2} = {}'.format(Y, 4, Y*4))
print('{} X {:2} = {}'.format(Y, 5, Y*5))
print('{} X {:2} = {}'.format(Y, 6, Y*6))
print('{} X {:2} = {}'.format(Y, 7, Y*7))
print('{} X {:2} = {}'.format(Y, 8, Y*8))
print('{} X {:2} = {}'.format(Y, 9, Y*9))
print('{} X {:2} = {}'.format(Y, 10, Y*10))
print('_'*16)